# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from last_page import Ui_LastWindow


class Ui_SecondWindow(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui =Ui_LastWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        SecondWindow.destroy()

    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(899, 526)
        self.temp = QtWidgets.QLabel(SecondWindow)
        self.temp.setGeometry(QtCore.QRect(310, 190, 251, 161))
        self.temp.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temp.setFont(font)
        self.temp.setTextFormat(QtCore.Qt.AutoText)
        self.temp.setAlignment(QtCore.Qt.AlignCenter)
        self.temp.setObjectName("temp")
        self.pushButton = QtWidgets.QPushButton(SecondWindow)
        self.pushButton.setGeometry(QtCore.QRect(140, 400, 241, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(SecondWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 400, 241, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.hum = QtWidgets.QLabel(SecondWindow)
        self.hum.setGeometry(QtCore.QRect(270, 40, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.hum.setFont(font)
        self.hum.setTextFormat(QtCore.Qt.AutoText)
        self.hum.setAlignment(QtCore.Qt.AlignCenter)
        self.hum.setObjectName("hum")

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "SecondWindow"))
        self.temp.setText(_translate("SecondWindow", "-"))
        self.pushButton.setText(_translate("SecondWindow", "사진 촬영"))
        self.pushButton_2.setText(_translate("SecondWindow", "배지 확인"))
        self.hum.setText(_translate("SecondWindow", "선을 배지에 맞추어 주세요"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
